;;; Exercise 2.2
;;; ============

(define (make-segment p1 p2)
  (cons p1 p2))
(define (start-segment s)
  (car s))
(define (end-segment s)
  (cdr s))
(define (midpoint-segment s)
  (make-point (/ (+ (x-point (start-segment s))
                    (x-point (end-segment s))) 2.0)
              (/ (+ (y-point (start-segment s))
                    (y-point (end-segment s))) 2.0)))

(define (make-point x y)
  (cons x y))
(define (x-point p)
  (car p))
(define (y-point p)
  (cdr p))
(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))

(define p1 (make-point 1 3))
(define p2 (make-point 2 4))
(define seg (make-segment p1 p2))
(define mid-p (midpoint-segment seg))
(print-point mid-p)

